---
# Tasks to configure iptables rules

- name: determine if iptables is installed
  command: iptables --version
  register: iptables_installed
  ignore_errors: true
  changed_when: false

- name: check to see if there is an iptables config file
  file: path=/etc/sysconfig/iptables
  ignore_errors: true
  changed_when: false
  register: iptables_exists
  when: iptables_installed.rc == 0

- name: ensure iptables config file exists
  shell: /sbin/service iptables save creates=/etc/sysconfig/iptables
  when: iptables_installed.rc == 0

- name: insert iptables rule for httpd (port 443)
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="^.*INPUT.*tcp.*443.*ACCEPT" insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 443 -j ACCEPT"
  when: iptables_installed.rc == 0 and iptables_exists.state != 'absent'
  notify: restart iptables

- name: insert iptables rule for httpd (port 80)
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="^.*INPUT.*tcp.*80.*ACCEPT" insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 80 -j ACCEPT"
  when: iptables_installed.rc == 0 and iptables_exists.state != 'absent'
  notify: restart iptables

- name: insert iptables rule for httpd (port 8080)
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="^.*INPUT.*tcp.*8080.*ACCEPT" insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 8080 -j ACCEPT"
  when: iptables_installed.rc == 0 and iptables_exists.state != 'absent'
  notify: restart iptables
